name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: ./
        with:
          root_file: Qinfo.tex
          working_directory: ./
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: appunti
          path: Qinfo.pdf
